Roguelike 1
alefedor/full_metal_rogue pull request #2
Opened 2019-04-04 15:28 UTC by sharkovadarya

2019-05-01 10:52 UTC, ArtyomLobanov requested changes
1. Добавьте комментарии ко всем классам и публичным методам
2. Добавьте ещё пару тестов на сериализацию
3. Где можно найти документацию?

2019-05-01 10:52 UTC, ArtyomLobanov commented on build.gradle
> +        attributes 'Main-Class': 'ru.hse.sd.full_metal_rogue.MainK'
1. Main лежит в пакете ru.hse.**spb**.sd.full_metal_rogue
2. MainK**t**

2019-05-01 10:52 UTC, ArtyomLobanov commented on build.gradle
> +    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
>C:\practice\games\fedorov-sharkova-kazakov\full_metal_rogue>java -jar build\libs\full_metal_rogue-1.0-SNAPSHOT.jar
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/TypeCastException
        at ru.hse.spb.sd.full_metal_rogue.Game.<init>(Game.kt:23)
        at ru.hse.spb.sd.full_metal_rogue.MainKt.main(main.kt:6)
        at ru.hse.spb.sd.full_metal_rogue.MainKt.main(main.kt)
Caused by: java.lang.ClassNotFoundException: kotlin.TypeCastException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more

https://stackoverflow.com/questions/54412334/gradle-implementation-vs-compile-in-jar-task

2019-05-01 10:52 UTC, ArtyomLobanov commented on src/main/kotlin/ru/hse/spb/sd/full_metal_rogue/Game.kt
> +class Game : JFrame(), KeyListener {
Зачем показывать наружу лишний интерфейс? Ситуация, в которой кто-то извне пользуется этим классом как KeyListener-ом, выглядит довольно странно. Может лучше спрятать это в приватный внутренний класс? Ну или вообще анонимным классом обойтись.

2019-05-01 10:52 UTC, ArtyomLobanov commented on src/main/kotlin/ru/hse/spb/sd/full_metal_rogue/map/FileMapLoader.kt
> +            null
Если попробовать открыть случайный файл, то всё хорошо - показывается сообщение об ошибке и приложение продолжает работу. Но если попробовать открыть файл, в котором сохранено что-то в формате json, но не ваша карта, то в консоль вылетает ошибка, а приложение перестаёт работать
Например, попытка загрузить файл, содержащий только `{}`, приводит вот к такой ошибке:
https://pastebin.com/e46pcprS

2019-05-01 10:52 UTC, ArtyomLobanov commented on src/main/kotlin/ru/hse/spb/sd/full_metal_rogue/scene/handler/LevelSceneHandler.kt
> +                        }
Не очень хорошо, что очерёдность ходов определяется положением существа. Получается, что справа налево можно убежать от моба, а слева направо - нет.

2019-05-01 10:52 UTC, ArtyomLobanov commented on src/main/kotlin/ru/hse/spb/sd/full_metal_rogue/ui/UIDrawer.kt
> +    fun outputStartMessage() {
А вы под каждое меню тут будете отдельный метод создавать? Не хорошо, что один класс на себя всю функциональность берёт. Может сделать несколько реализаций - по одной для каждого типа сцен. Или реализовать тут какой-то общий интерфейс, а конкретные реализации перенести в соответствующие хендлеры?

2019-05-01 13:28 UTC, alefedor commented on build.gradle
> +        attributes 'Main-Class': 'ru.hse.sd.full_metal_rogue.MainK'
Ну да, здесь была опечатка, которую никто не заметил, потому что все пользовались Idea.

2019-05-01 13:29 UTC, alefedor commented
Ссылки на документацию:
https://docs.google.com/document/d/1HpQjP8WQ0GTn4GEyNnIqFmNsjRAUV84yV7wHbFEV_AA
https://drive.google.com/open?id=1YPjlkb6bakqV4ijyeQ3tygFl7m0auiT3

2019-05-01 13:35 UTC, alefedor commented
@ArtyomLobanov 
> 1. Добавьте комментарии ко всем классам и публичным методам
В последнем (третьем Roguelike) уже есть комментария ко всем классам. 
Предлагаете скопировать их еще и сюда?

> 2. Добавьте ещё пару тестов на сериализацию
> 3. Где можно найти документацию?
Ссылки на документацию добавил, но не удивляйтесь, что она слишком новая, учитывая, что дедлайн сдачи этого задания был 14-го марта.

2019-05-01 13:53 UTC, alefedor commented on build.gradle
> +    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
Поправил, теперь jar запускается нормально

2019-05-01 14:00 UTC, alefedor commented on src/main/kotlin/ru/hse/spb/sd/full_metal_rogue/scene/handler/LevelSceneHandler.kt
> +                        }
Кажется, что в последней версии всегда сначала ходит игрок, а потом враги. Для этой версии, чье задании вообще не включает движение врагов, и этот код работает идеально, а упомянутой выше проблемы не возникает, потому что движется только игрок.

2019-05-01 14:50 UTC, ArtyomLobanov commented
> @ArtyomLobanov
> 
> > 1. Добавьте комментарии ко всем классам и публичным методам
> 
> В последнем (третьем Roguelike) уже есть комментария ко всем классам.
> Предлагаете скопировать их еще и сюда?
> 
> > 1. Добавьте ещё пару тестов на сериализацию
> > 2. Где можно найти документацию?
> 
> Ссылки на документацию добавил, но не удивляйтесь, что она слишком новая, учитывая, что дедлайн сдачи этого задания был 14-го марта.

1. Про комментарии: loading...
2. Google Docs логируют все изменения. Владелец документа может вернуться к любой версии.
![image](https://user-images.githubusercontent.com/9067686/57021113-05a04700-6c34-11e9-9609-7e94ac0aad9b.png)
![image](https://user-images.githubusercontent.com/9067686/57021118-09cc6480-6c34-11e9-9653-20292aeeda98.png)

2019-05-01 15:12 UTC, ArtyomLobanov commented
Комментарии можно не копировать

2019-05-13 21:06 UTC, DmKazakov commented
@ArtyomLobanov а можно не синхронизировать мертвые ветки и добавлять исправления только в актуальную? Поправил какие-то замечания сейчас там.

2019-06-08 08:16 UTC, ArtyomLobanov commented
Да, дальше будет работать только с актуальной веткой. Если тут остались какие-то исправления, перенесите их, пожалуйста, в основную ветку.

2019-06-08 08:35 UTC, alefedor commented
@ArtyomLobanov , все перенесено в актуальную ветку. Можно проверять.

2019-06-22 12:13 UTC, closed without merging